services:
  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000

  database:
    image: postgres:latest
    environment:
      PGDATA: /var/lib/postgresql/data/db_data/
      POSTGRES_DB: contacts
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d contacts"]
      interval: 10s
      timeout: 5s
      retries: 5
