services:
  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000

  database:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: team_availability_db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: