services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # This Dockerfile will build the frontend
    volumes:
      - ./frontend/dist:/app/dist  # Share the built frontend with the home machine
    command: pnpm run build 

  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy
      frontend:
        condition: service_completed_successfully

    volumes:
      - ./frontend/dist:/app/frontend/dist

  database:
    image: postgres:16.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: testdbuser
      POSTGRES_PASSWORD: testdbpassword
      POSTGRES_DB: team_availability_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./frontend/dist:/app/frontend/dist
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testdbuser -d team_availability_db"]
      interval: 10s  # Check every 10 seconds
      timeout: 5s    # Timeout after 5 seconds
      retries: 5     # Try 5 times before marking as unhealthy

volumes:
  pgdata: